version: '1.0'

services:
  service1:
    build:
      context: ./service1
    container_name: service1
    ports:
      - "8081:8080"

  service2:
    build:
      context: ./service2
    container_name: service2
    ports:
      - "8082:8080"
    depends_on:
      - service1
